### ISSUE TITLE
Camcorder isn't working

### ISSUE THREAD

**Issue by m-chojnacki** [MaclawStudio/aosp#1]
Camcorder isn't working for now. If you found any app that can record video on our ROM, please post it here. It will help us.

**Comment by yousseefs** [comment]
Videocam illusion?

**Comment by immamex** [comment]
Videocam illusion works well

**Comment by doomsded** [comment]
Yes, Videocam illusion works well for me too.

**Comment by rcseven7** [comment]
Yes! "videocam illusion" is working.. but i think this because the output video format from "videocam illusion" is mov not mp4 like the others so we can just looking find another application as well the output is mov and that's will gonna works.

**Comment by gbr161** [comment]
Guys any chance to get stock camera working?

**Comment by maclaw** [comment]
Fixed in all our releases.
