### ISSUE TITLE
Problem with  alarm clock

### ISSUE THREAD

**Issue by DoBi** [MaclawStudio/aosp#100]
I am using my phone as alarm clock. With rc2 there was no problem, but with rc3 it rings only two times and the display goes on.
 Then it does nothing. I am using Alarmdroid.

**Comment by DoBi** [comment]
Ok. This morning my phone was connected to the charger and the alarm clock works. This is strange. I will test it the next days and post my results..

**Comment by DoBi** [comment]
Yesterday there was no problem with my alarmclock, too. But today it did not ring. Not only one time.
Only the display turned on.
I thing it has something to do with the batterie power. When the batterie is full there is no problem. But if it is in the red area, it slows down and the alarmclock do not work.

**Comment by maclaw** [comment]
Wipe. There's no problem with alarms.
