### ISSUE TITLE
Another Problem: Google Voice Typing (JB Alpha 1 - ACE)

### ISSUE THREAD

**Issue by ikikinoko** [MaclawStudio/aosp#102]
It occured when Google voice typing is also enable. I just wanted to reply a message and pressed voice input for sudden. The keyboard doesn't appear anymore, and then cause Google voice typing is stopped working.

Yea it's for a while, to avoid it with making Google voice typing disabled on keyboard and input method settings. Let Android Keyboard (AOSP) be default.

**Comment by ghost** [comment]
It's not actually Maclaw's fault :) We must live with not-working voice search on ours phones. Maybe some day....
