### ISSUE TITLE
[jellybean] USB mass storage doesn't work

### ISSUE THREAD

**Issue by immamex** [MaclawStudio/aosp#103]
When connecting device to computer and select USB mass storage, the system removes the SD, instead of connecting it to the computer

**Comment by rcolaco** [comment]
Here same happend (Alpha 2)

**Comment by Avaso** [comment]
confirm, please quick fix

**Comment by ghost** [comment]
Confirmed in my ace, alpha 2 too.

**Comment by Amatsugu** [comment]
same here, and settings app crashes when trying to enable it from there
