### ISSUE TITLE
Problemy Ice Cream Sandwich 4.0.4 (AOSP) RC3 dla GIO

### ISSUE THREAD

**Issue by lukgohan** [MaclawStudio/aosp#104]
Cześć

Wymienię w punktach problemy które u mnie występują:
1. Przy zmianie jasności ekranu w ustawieniach systemu, przyciski nawigacyjne: ten od menu i "back" cały czas świecą. Nawet jak się zablokuje telefon. Pomaga tylko restart.
2. Wi-fi włącza się bardzo długo, myślę że czterokrotnie dłużej niż w oryginale.
3. Nie działa wyszukiwanie głosowe w nawigacji i wyszukiwarce google, również dyktafony żadne nie działają, po użyciu dyktafonu przestaje działać słuchawka w telefonie tzn. jak dzwonie to ja słyszę rozmówce, on mnie nie. Pomaga tylko restart.

Pozdrawiam

**Comment by maclaw** [comment]
1. One issue per report.
2. On bugtracker you can write only in English.
