### ISSUE TITLE
bluetooth not working properly in (AOSP ICS RC3)

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#105]
SIR bluetooth not workin in ics rc3 galaxy ace.. when i try to send a file to another device .and when i click to send on that device it doesnt show anything on that device bout receving ...and  another device try send me a file it display file not sent.. unsuccessful...plz fix it waithing for ics aosp rc4...

**Comment by maclaw** [comment]
Use other file manager, like Total Commander.

**Comment by huzefa52** [comment]
thanks maclaw for replying...and waiting 4 ics aosp rc4 plz release fast ..thanks
