### ISSUE TITLE
[JBα2_cooper] Issues

### ISSUE THREAD

**Issue by skyfullofballoons** [MaclawStudio/aosp#108]
Hello there MaclawStudio.

Thanks for all the effort you put in to this project and really appreciate all your good work.

Since this is still in alpha stage, so it usual to see little bugs.

Please note that below are not complaints. Trying to help make the project better :) And I'm aware that this only takes a couple minutes to write a bug report, and it takes forever to compile and implement. Really want you to know that, appreciate your hard work; just wish I too knew about what you do :)

Bugs that I found:

1) Link2sd not working properly. Some apps cannot be linked to sd-ext. I've seen this happening in other ROMs but, I guess this is something that can be fixed. I found that it's a google jellybean issue, that it's using other ways to store app data. I've seen this happening in one of your earlier ICS ROMs, and it was eventually fixed.

2) USB debugging is not working. It's not recognizing the device itself on the adb command line.

3) Gallery seems to have issues recognizing images. It's showing videos thumbnails instead of image previews.

One suggestion though. Please add the reboot menu to power options :+1: 

:skyfullofballoons:

**Comment by ikikinoko** [comment]
For number 3, that wouldn't be matter for changing wallpaper. Just using file manager (such as Root Explorer) and open your own picture to use as wallpaper. That's my suggestion.

**Comment by maclaw** [comment]
1) No, it's limited by app.

One issue in one case.
