### ISSUE TITLE
[jellybean] GUI Sizes

### ISSUE THREAD

**Issue by dfsramos** [MaclawStudio/aosp#109]
The interface size overlaps on:
- SIM Card pin entering (number buttons overlap)
- Homescreen (the "desktop" overlaps with Google Search bar and Dock)

**Comment by maclaw** [comment]
Write to Google and ask why they don't support MDPI any longer.

**Comment by dfsramos** [comment]
Er.. 
First of all, don't get me wrong, I'm not complaining. I'm a developer myself and I know how tough it is to work on something and sometimes just see people complaining about it.

I do know the concept behind AOSP is to leave the code as it is.
The thing is that this way, it's really weird to even use it.

Wouldn't you be able to tweak the launcher or something like that to stop this overlapping?
After all, porting HDPI code to MDPI device should involve tweaking the GUI to be compliant with those very same MDPI devices, no?

Thanks in advance for all your hard work, and please understand I'm not complaining. Just trying to get an amazing thing even better!

**Comment by ghost** [comment]
Maybe this is the problem:

https://code.google.com/p/android/issues/detail?id=5214&q=mdpi&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

which is a Google problem not Maclaw's problem, but I think you made a valid point @dfsramos
