### ISSUE TITLE
[jellybean] Missing Reboot menu

### ISSUE THREAD

**Issue by dfsramos** [MaclawStudio/aosp#110]
Missing reboot option on shutdown menu.

**Comment by ikikinoko** [comment]
For reboot, it's none since alpha 1 (might because of AOSP). I can't predict it, ask to maclaw or marcin for this problem.

**Comment by maclaw** [comment]
It's AOSP. Why are you reporting it as bug?

Get real, guys.

**Comment by dfsramos** [comment]
@maclaw I'm not saying it's a bug. I don't know the exact inner works of AOSP. I didn't report it as a bug and this tab is not only about bugs, it's about issues. 
I apologize for reporting something that isn't a bug. I can stop reporting anything I find if that's what you want, but I think it's better to get non-bugs reported among some real bugs, than to get nothing reported and miss real bugs, right?

Best regards!
