### ISSUE TITLE
[jellybean]Wi-Fi

### ISSUE THREAD

**Issue by Avaso** [MaclawStudio/aosp#111]
[jellybean]Wi-Fi turns off in sleep mode.

**Comment by fantostisch** [comment]
Yu can put this of in settings>wifi>menu>advanced

**Comment by Avaso** [comment]
Unfortunately it doesn't  work. I've tried all modes and still turns off in sleep mode.

**Comment by Avaso** [comment]
The same is true in the case of data transmission.

**Comment by Avaso** [comment]
Sorry, it's my fault. That was set in the GO Power Master.
