### ISSUE TITLE
[jellybean] Gallery shows every image as a video

### ISSUE THREAD

**Issue by deliantwo** [MaclawStudio/aosp#112]
The Gallery application shows every image as a video. If you take a picture you can see it right in the gallery but, if somethig else read the same file ( for example quickpic, but also copy it through a file server ) the gallery see it as a video.
Clearly you cannot play the "video".
This happens only with the pictures taken with the Camera stock app. With CameraFX the picture in the folder FxCamera are always visible, probably because there are no metadata in those pics.
![Screenshot_2013-03-10-17-51-22](https://f.cloud.github.com/assets/3824581/241313/3a07c542-89a3-11e2-9af0-3988b29887fd.png)

**Comment by ghost** [comment]
Confirmed in my ace, alpha 2, too.
