### ISSUE TITLE
[ICSFINAL1ace] Bugs

### ISSUE THREAD

**Issue by menboi1** [MaclawStudio/aosp#113]
> Google Play Services force close
> Panoramic Camera so laggy NOT IMPORTANT:p
> Still button backlight keep on when lock the phone (sometimes)

Apparently is all
The best rom i have flashed 
Thanks team!!!

**Comment by under3415** [comment]
I am getting Google Play Service FCS as well (on GIO ICS final1). After uninstalling an app it seems. Stops after a Reboot
Will post logcat later...

**Comment by under3415** [comment]
Here is the logcat (GIO ICS final1)
https://gist.github.com/5159424

**Comment by maclaw** [comment]
One bug per report.
