### ISSUE TITLE
[ICS Final 1] PPTP VPN not working / No TUN.KO file for DroidVPN & OpenVPN

### ISSUE THREAD

**Issue by SilenZ1** [MaclawStudio/aosp#118]
PPTP VPN and DroidVPN/OpenVPN is not working on any of the ICS/JB builds. 
There is no tun.ko compiled specially for this ICS builds. So absolutely no VPN support is available on any ICS (and JB) build because no PPTP or OpenVPN-DroidVPN is possible..

Could you please provide a compiled tun.ko for the ICS Final and if possible also for the JB releases. Also standard Android VPN support (PPTP) would be nice.

**Comment by MardonHH** [comment]
Use tun.ko installer from market!

**Comment by SilenZ1** [comment]
tun.ko installer from the market will install a tun.ko file BUT the phone hangs when using it. Because the tun.ko must be compiled for the specific kernel. The kernel you guys compiled for these builds is not working with these provided tun.ko files. I have tried multiple tun.ko files. none of them is not crashing when using it.

If you could provide us one, I would be very gratefull!
Date: Wed, 13 Mar 2013 12:16:45 -0700

**Comment by SilenZ1** [comment]
By the way: The ICS RC2 had the tun.ko file in it and it worked like a charm. On RC3 the kernel was completely rewritten from scratch, that's when the problems above mentioned started.

**Comment by SilenZ1** [comment]
Please accept this issue/request. Only you guys can make this work with your special compiled kernel
