### ISSUE TITLE
ics final bug...4  bugs in a row

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#122]
maclaw 

1.st bug  bluetooth is not working properly...no one can send me a file via bluetooth neither do i....

2nd. bug ...in camera there is no zooming option and in video recording when we start record flashlight doest not open

3rd. bug is after changing brightness ..backlight softkey lights remain open after screen off

4th bug is that panorama mode is laggy in camera.. n very slow panorama mode...

maclaw & marcin plz fix bluetooth ..it is very important.. on galaxy ace

thanks for ur awesome work...

**Comment by maclaw** [comment]
One bug per report.
