### ISSUE TITLE
GIO ICS Final 1 - Google Play FCS

### ISSUE THREAD

**Issue by under3415** [MaclawStudio/aosp#124]
Getting Google Play forced closures after uninstalling an app. Problem stops after a reboot.

Upgraded from RC3 and done Delvik wipe (no factory reset). Were not getting this in RC3.

Logcat here: https://gist.github.com/5159424

Regards
Dejan

**Comment by SilenZ1** [comment]
Same issue here

**Comment by maclaw** [comment]
Wipe is unnecessary in your case.
