### ISSUE TITLE
(ics final 1) bluetooth bug

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#125]
maclaw bluetooth is not working properly .....plz fix wen some1 try to send me a file it say file send unsuccessful..and wen i send a file it shows nothing no accept or decling popup in other device..if u want video of this bug i will show u...

plz fix it ..its a true bug

**Comment by f0ntes** [comment]
True, same problem here on gio...

**Comment by maclaw** [comment]
Use other file manager to send file.

**Comment by huzefa52** [comment]
yes maclaw i am using total commander an m able to send file but... m not able to receive  maclaw in ics aosp final 1
