### ISSUE TITLE
(ics final1) speech to text issues

### ISSUE THREAD

**Issue by fomay** [MaclawStudio/aosp#128]
I cannot get speech input (microphone button) work on my Galaxy Gio.

The pop-up opens but does not receive any input from the microphone or headset. I tried Google search widget, the microphone buttons of stock and custom keyboards and speech-only input method, no luck.

When I install an older version of the stock app via backup (ics-final1 comes with version 3.0.1, I replaced it with 2.1.3 Gingerbread version [even a Froyo version will do the trick]), the speech input button works everywhere until I reboot the phone because it automagically restores the 3.0.1 version.

And of course, the microphone is working correctly, only the speech to text program is not working.

**Comment by ghost** [comment]
I confirm. By the way, the team of MoltenMotherBoard uses the older version of the speech-to-text app in their AOSP ICS.
