### ISSUE TITLE
Whatsapp image problem

### ISSUE THREAD

**Issue by luukvideo** [MaclawStudio/aosp#13]
You cant send any pictures using whatsapp it says: out of memory. when you put it to 2 MP it works just fine.

**Comment by maclaw** [comment]
App issue, but we'll try to edit dalvik settings in next release.

**Comment by luukvideo** [comment]
Ok thanks maclaw!

**Comment by s4m4n** [comment]
I've been trying many ROMs , I hadn't have this issue with any on Viber or Whatsapp.
even if you take a new picture or try sending one from the gallery it says our of memory !

**Comment by luukvideo** [comment]
As maclaw said it has something to do with the dalvik settings i guess in build.prop some thing is set to low memory

**Comment by s4m4n** [comment]
well , does anyone have an idea about how to fix this meanwhile before maclaw' studio release the new version?

**Comment by luukvideo** [comment]
I will try messing with the build.prop if it works i will post it here

**Comment by Otebb** [comment]
put a higher value in this line dalvik.vm.heapgrowthlimit=18m or simple delete it, at least this solve the problems in viber and whatsapp.

**Comment by s4m4n** [comment]
I just set dalvik.vm.heapgrowthlimit to 48M and it solved the problem for me . I hope that Maclaw would apply this fix for further releases.

Thanks all !

**Comment by maclaw** [comment]
Yeah, in next release it's fixed.
