### ISSUE TITLE
(ICS Final 1) Opera Mini/Mobile compatibility issues

### ISSUE THREAD

**Issue by benjaminzer** [MaclawStudio/aosp#130]
This is based on the S5830 version of AOSP ICS Final 1

There's a problem whenever I surf with Opera Mini or Mobile.
In Opera Mini
...the soft keyboard suddenly goes black. And when I press elsewhere in the browser nothing happened. And as I bring down the notification drawer, I can only see the date and the settings button. The section below was "cut". When pressing the home button, it was still stuck there and can't go back t the home screen. I had to go to Settings and go back to Opera Mini to use the browser again. This sort of ticked me off.

In Opera Mobile
When I browse for a while, the browser suddenly gone blank. When I try going to settings and go back to Opera Mobile (the same trick I did on Mini), the browser was still blank. There was no workaround to get through this. So I gave up.

Yes, these browsers are all backup with Titanium Backup. They're already updated, and they work well with other ROMs even if I'm to restore them with Titanium Backup.

Opera is the only browser I rely upon when using Galaxy Ace. Firefox and Chrome is not for armv6. Dolphin Browser is pretty too slow. And so is the stock Browser. Also, I have to use Opera Mobile for some web pages. Mini is not 100% reliable at times. It won't work with my college's wifi.

This ROM is my favorite. Very snappy. But if only the problems are solved.
Any help will be appreciated. 
Thanks for reading.

**Comment by MardonHH** [comment]
Firefox is also available for ARMv6 since august 2012 !

See here: http://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-central-android-armv6/

**Comment by benjaminzer** [comment]
Thanks MardonHH. I used to try their Fenenc build before. It ate my internal memory a lot. But will this build you gave me be different?

**Comment by MardonHH** [comment]
You can move firefox to ext sd with link2sd.
