### ISSUE TITLE
cm_cooper-ota-eng.final1 - Video Bugs

### ISSUE THREAD

**Issue by ghost** [MaclawStudio/aosp#133]
Netflix App plays for 5 sec then stops, I hear sound, but no video. Netflix app does work in Gingerbread 2.3.6 for me.
Youtube HQ is also choppy, issues seem related.

**Comment by MardonHH** [comment]
OMX lib related

**Comment by maclaw** [comment]
OMX lib related. We cannot do anything with that.

**Comment by dundee-81** [comment]
Is it possible to port this library from another ROM, e.g. from CM10.1?
I'm using ROM from this site http://forum.xda-developers.com/showthread.php?t=2104442 and YouTube HQ works like a charm.

**Comment by socialsb** [comment]
but why do you have "YouTube HQ" under "what works" if it actually doesn't?
