### ISSUE TITLE
Instagram not working properly.

### ISSUE THREAD

**Issue by Androiderr** [MaclawStudio/aosp#134]
When i ever try to add filter in a picture. The whole screen gets black at that point and only editing options appear and sometimes after editing a picture the picture appears a black black image in the gallery when in it is saved. This problem is in AOSP (FINAL 1).

**Comment by benjaminzer** [comment]
Same here! I have to lower the crop just to have it viewable. :/

**Comment by maclaw** [comment]
3rd party app issue. We don't have camera sources, so there's no possibility to fix in from our side.
