### ISSUE TITLE
Internet tethering isn't working

### ISSUE THREAD

**Issue by marcossousa** [MaclawStudio/aosp#14]
Hi,

I'm using ICS 4.0.4 Beta 1 and my Internet tethering ins't working. I'm able to configure but nothing happens.

I'm a develper too, is there a way to grap the system error log?

**Comment by MardonHH** [comment]
try open garden wifi tether app from market for now

**Comment by maclaw** [comment]
Maybe it's time to update to RC1? There's working native wifi tether....
