### ISSUE TITLE
(ICSFINAL CM9) Galaxy Ace Button LED On

### ISSUE THREAD

**Issue by guilherme-blatt** [MaclawStudio/aosp#142]
When I lock my galaxy ace, the led buttons are still on. Please help

**Comment by ghost** [comment]
I have the same issue with Galaxy GIO and with AOSP final.
Can I somehow help you to fix this issue ?

**Comment by jbaanus** [comment]
Same here, seems to be related to changing screen brightness.

**Comment by ghost** [comment]
Yes, that's right. 
A known workaround is to use some software to disable the led, while you change the brightness, as I don't need those lights at all fits for me... but if I can anyhow help your works (not your, but their I mean Maclaw Std.) please let me know.

link to the workaround:
http://maclaw.pl/2013/03/12/aosp-ics-final-release-is-here/#comment-11012

**Comment by guilherme-blatt** [comment]
thanks everyone for the help. Another soluition i found was to reboot, but i'll see mspike one. (sry 4 my english)

**Comment by ghost** [comment]
Why closed ? Did you get some real solution ?
