### ISSUE TITLE
(ICS Final 1) Video recording at 320x240

### ISSUE THREAD

**Issue by benjaminzer** [MaclawStudio/aosp#144]
This issue is about the S5830 version of AOSP ICS Final 1.

Yes. This is also a common problem to all ICS/JB ROMs for S5830. Probably this is on other armv6 phones too (although I heard x10 mini does not have such thing). This isn't exactly a problem. Camera recording is smooth. But it only records at 320x240. And S5830 can record at 640x480, but for this case, only Gingerbread or even Froyo ROMs allows high res recording. Will be great if you guys can manage to implement HQ recording on Ace.

Thank you for reading. Hope you'll consider this.

**Comment by SilenZ1** [comment]
+1 for this. Would be awesome to have on this ROM.

**Comment by maclaw** [comment]
We cannot do anything.

Gingerbread also wasn't be able to make video in 480p (Samsung did something wrong in GB libs). We need to use GB libs (there's no camera sources), so there's no possibillity to make resolution higher.

**Comment by benjaminzer** [comment]
I thought the resolution was in 640x480 as I recorded with GB ROMs. Only in ICS/JB ROMs its at 320x240. Of course, I don't mean 720x480 and beyond :P
