### ISSUE TITLE
(aosp ics final 1) bluetooth receving problem

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#154]
maclaw only bug is that we cannot receive anything from another device....... only we can able to send file

plz fix it 

thanks maclaw & marcin ..u both providing stable aosp ics....and + faster and smoother

**Comment by SilenZ1** [comment]
+1, same problem here on GIO

**Comment by eliezeramon** [comment]
i can only retrieve file. .i cant send file
