### ISSUE TITLE
Issue CM9 : phone laggy as hell while wifi on, but there's no wifi connection 

### ISSUE THREAD

**Issue by junnickbefore14** [MaclawStudio/aosp#156]
When I turn on wifi in area that there's no wifi connection, sometimes my phone become laggy. When I check, netd takes high cpu usage. I've already googling for this problem but no luck. I've also ask to somebody, they call it netlink event.
The only way to solve this problem is restart the phone and disable wifi
Could u please fix this problem? 
Thx in advance

**Comment by GregAce** [comment]
I have this issue too, with all ICS and JB roms I tried until now. It's very annoying for me (have to kill netd process when occurs)
