### ISSUE TITLE
(AOSP ICS Final 1 S5830) Notification drawer gets buggy at times 

### ISSUE THREAD

**Issue by benjaminzer** [MaclawStudio/aosp#157]
Sometimes, like after a day of the phone being switched on, the notification drawer doesn't work properly. I received a Whatsapp message. And the icon shown of the top left. But it either shows nothing or other outdated notifications when I slide the bar down. Can't even slide off or kill any of them.

Hope you'll put this in regard. Thank you for reading :)

**Comment by fantostisch** [comment]
Same isseu on my ace

**Comment by SilenZ1** [comment]
Same here on GIO

**Comment by eliezeramon** [comment]
+1
