### ISSUE TITLE
{jellybean} SIM PIN

### ISSUE THREAD

**Issue by blugonjic** [MaclawStudio/aosp#158]
When entering SIM PIN the number overlap and are too small. It is possible to enter PIN but it looks bad.

**Comment by TEOn00b** [comment]
It's because Google doesn't have suport for MDPI anymore...

**Comment by dfsramos** [comment]
This should be fixed if possible. Porting something involves porting resources as well. Is it impossible to do?

**Comment by huzefa52** [comment]
yea...same here it should be fix in next release....aosp jb beta 2 ...its look very small pin numbers

maclaw & marcin plz fix it as soon as possible anyway thanks to u both

**Comment by SilenZ1** [comment]
+1 if possible. I can live without it though :-)

**Comment by blugonjic** [comment]
Yes, I find it perfectly fine. I can live with it. Just wanted to commit to bugtracker
