### ISSUE TITLE
[AOSP Jellybean beta1] Gallery app not functioning as expected

### ISSUE THREAD

**Issue by SilenZ1** [MaclawStudio/aosp#160]
Images are all treated as video's and therefore cannot be displayed at all in gallery app. This was also the case in Jellybean Alpha 1 and Alpha 2 versions.

**Comment by SilenZ1** [comment]
In addition to above post: please fix this issue. It is correctly working on all ICS builds. Keeps me and probably many others from using this build. Thats a shame because the ROM is very fast! :-)

**Comment by deliantwo** [comment]
Same issue here

**Comment by kymkeive** [comment]
In addition the other issues menioned I have noticed that my latest photos aren't being auto added to galery, even when I use "refresh" from the main options menu.

**Comment by ghost** [comment]
Wallpaper of MaclawStudio is displayed properly: http://maclaw.pl/2013/03/13/maclawstudio-wallpaper-2/

It is a PNG, while most unworking images are JPEG.

**Comment by janez33** [comment]
Same issue here, all works perfectly i can't wait to load Jelly bean final release!!! :D

**Comment by Twarx** [comment]
I use "QuickPic" as an alternative for the gallery, but this app has also problems showing the pictures taken with the camera. So the issue is probably not only the Gallery app, but also the images taken by the camera.
