### ISSUE TITLE
[jellybean beta1] SD-ext not mounting

### ISSUE THREAD

**Issue by blugonjic** [MaclawStudio/aosp#161]
the filesystem cannot mount SDext as no cronmod script or S2e will work

**Comment by ghost** [comment]
Gio does not have much internal space, so a lot of people use INT2EXT+ and other init.d scripts of this kind. I think support of init.d scripts would be useful in the ROM.

**Comment by blugonjic** [comment]
AOSP does not have init.d support but it is easily added and all AOSPs from Maclaw work with added init.d. CM ROMs have init.d and work with INT scripts. Only this ROM has problems sadly. Let's hope the dev will fix it
