### ISSUE TITLE
 [AOSP] Jellybean Beta1 BLN & Sim Layout

### ISSUE THREAD

**Issue by xwinnernikx** [MaclawStudio/aosp#164]
Hey Maclaw Hey Marcin :)
The BLN App say´s BLN is not supported and 
the Layout for Simcard is a little squized :D 
Thanks for your development guys :+1:

**Comment by GregAce** [comment]
BLN control does not work with this kernel, dunno why. You can try NStools, it works for me.

**Comment by xwinnernikx** [comment]
Thanks
