### ISSUE TITLE
[AOSP] Jellybean Beta1 - FC Settings (apk) in Storage

### ISSUE THREAD

**Issue by tomaasz** [MaclawStudio/aosp#165]
FC Settings (apk) in Storage (during calculation)

**Comment by kymkeive** [comment]
Yes, same here, always FC after a few seconds of calculation...

**Comment by ghost** [comment]
I can confirm and have logcat for that:

http://pastebin.com/ibWanG0T

Edit: Just to clarify, the issue affects my s5830 cooper

**Comment by janez33** [comment]
Same problem here.
