### ISSUE TITLE
Phone Call Issue

### ISSUE THREAD

**Issue by richardxtc** [MaclawStudio/aosp#17]
Since flashing RC1 i have had this weird issue when i receive a call, sometimes the phone doesnt dial and the person i am phoning just answers and then sometimes the begining of the phone call makes alot of weird sounds such as an old dial up modem and then clears up later.

**Comment by richardxtc** [comment]
Why would you flag this as false? I am having this problem?

**Comment by maclaw** [comment]
It's not related to our ROM. I can't reproduce it, no one else reporting. so, everything telling me that's a false issue.

**Comment by richardxtc** [comment]
Ok fair enough. I will try reflash and see if the problem persits.
