### ISSUE TITLE
[AOSP Jelly Bean Alpha 2] Can't access recovery mode

### ISSUE THREAD

**Issue by Flxrent** [MaclawStudio/aosp#172]
When rebooting with the keys home+vol up+power the phone stays on "samsung" screen with the inscription "RAMDUMP Mode (ARM9 mode)" on the left corner and never enters in recovery mode.

**Comment by ghost** [comment]
What you did is NO WAY to enter the recovery; I wonder how you got the ROM installed.

The Way to Gio/Ace Recovery has always been 'Home + Power until the Recovery Boots'.

**Comment by Flxrent** [comment]
Well i don't don't know why i was so sure that i needed to press vol up... Sorry about that  and thanks !
