### ISSUE TITLE
(AOSP ICS FINAL 2) BLUETOOTH apk file receving  problem

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#178]
maclaw & marcin u both rock but..since from aosp ics rc3 m keep on telling there is bluetooth receving problem only wen we send apk file from other device to our device ..only we can send a file
guys any1 else expecting this issue on galaxy ace

plz fix it or release any patch for bluetooth ..

reply maclaw & marcin

**Comment by mexipower** [comment]
i cant send or receive files with the extension APK, from any android....
try renaming to .mp3, then in your phone rename to .apk
