### ISSUE TITLE
status bar bug 

### ISSUE THREAD

**Issue by raymuy** [MaclawStudio/aosp#18]
hey maclaw.
sometimes when i pull down the status bar from the lock screen 
the status bar doesn't comes all the way down so i cant see my notifications. i have to do reboot to make it work.
can you fix it?

**Comment by marius500** [comment]
Indeed i got this too and same with lockscreen sometime's it doesn't appear

**Comment by alexelpan** [comment]
this happen to me few days ago, please re check this
