### ISSUE TITLE
[AOSP ICS final2] Battery drain fast

### ISSUE THREAD

**Issue by menboi1** [MaclawStudio/aosp#180]
The title say all

Thanks Maclaw Studio

**Comment by guilherme-blatt** [comment]
maybe the problem is with your battery. U can try to: 1% brightness, turn wifi off when not using and try juice defender.

**Comment by menboi1** [comment]
i dont think so, the battery is new , and juice defender is for save battery, but with my ace its draining, in five minutes the percent 90% go to 78% and i do all the forms of calibration but not work, and then i say: "ok its my battery problem", but i flash another rom and the battery is good. i dont know what i do bad

Sorry for my bad english

**Comment by jcperes** [comment]
Battery is draining just like in Final 1. If there is an improvement, I can't tell. But I think it did'nt get worse either!
