### ISSUE TITLE
[AOSP ICS final2] CAMERA (galaxy ace)

### ISSUE THREAD

**Issue by rohitdessai** [MaclawStudio/aosp#186]
The camera is working great EXCEPT panaroma..its very laggy..and there is no flash for recording videos? :(  pls if u can fix this it would be the best ROM and it still is.. ;)

**Comment by guilherme-blatt** [comment]
panaroma was never good on maclaw ROMs (at least ICS), I sugest using an app from google play. And for the video recording not sure what u need.

**Comment by rohitdessai** [comment]
thanks
