### ISSUE TITLE
[AOSP ICS FINAL2] More lagy then FINAL1

### ISSUE THREAD

**Issue by tomaasz** [MaclawStudio/aosp#188]
I've installed AOSP ICS FINAL2 3 times todays. It is always more lagy for me then FINAL1.
I use Link2SD. Before all installations I made all wipes and format sd-ext.

**Comment by guilherme-blatt** [comment]
if u move important apps to sdcard it will be laggy. Other than that I cant help u a lot.

**Comment by tomaasz** [comment]
I have not moved important apps to sdcard. I have very similar to FINAL1 apps structure, and with FINAL1 I didn't have lags like in FINAL2

**Comment by huzefa52** [comment]
+1 same here it is more laggy in ics final 2 ... ics final 1 was fast.....

maclaw & marcin hope u will improve speed for galaxy ace
