### ISSUE TITLE
Gallery doesn't work sometimes

### ISSUE THREAD

**Issue by grkngrn** [MaclawStudio/aosp#19]
while looking photos, it says gallery stopped working..

**Comment by ghost** [comment]
It happens also with me and I don't have more than 50 photos. Also, sometimes I try to see full photo it just says 'No Thumbnail'.

**Comment by ghost** [comment]
From logcat, I get lots of:

D/skia    ( 4178): --- decoder->decode returned false
W/JobLimiter( 4178): error executing job: com.android.gallery3d.data.LocalImage$LocalImageRequest@410d4e60
W/JobLimiter( 4178): java.lang.OutOfMemoryError
W/JobLimiter( 4178):    at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
W/JobLimiter( 4178):    at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:424)
W/JobLimiter( 4178):    at com.android.gallery3d.data.DecodeUtils.requestDecode(DecodeUtils.java:75)
W/JobLimiter( 4178):    at com.android.gallery3d.data.ImageCacheRequest.run(ImageCacheRequest.java:56)
W/JobLimiter( 4178):    at com.android.gallery3d.data.LocalImage$LocalImageRequest.run(LocalImage.java:157)
W/JobLimiter( 4178):    at com.android.gallery3d.data.ImageCacheRequest.run(ImageCacheRequest.java:28)
W/JobLimiter( 4178):    at com.android.gallery3d.util.JobLimiter$JobWrapper.run(JobLimiter.java:112)
W/JobLimiter( 4178):    at com.android.gallery3d.util.ThreadPool$Worker.run(ThreadPool.java:124)
W/JobLimiter( 4178):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/JobLimiter( 4178):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/JobLimiter( 4178):    at java.lang.Thread.run(Thread.java:856)
W/JobLimiter( 4178):    at com.android.gallery3d.util.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)

**Comment by kaplanhkaan** [comment]
I have that issue too 'No Thumbnail'.

**Comment by maclaw** [comment]
Solved in RC2.
