### ISSUE TITLE
haptic feedback can't turned off

### ISSUE THREAD

**Issue by empty4u** [MaclawStudio/aosp#193]
I like your ROMs for my Galaxy Ace but the haptic feedback is a real show stopper. Everytime I use the keyboard there is vibration. And yes I turned off haptic feedback in system settings and made a reboot. But it doesn't work. I tried disabling every vibration setting I found. There is no way to get the keyboard quiescent. :o(
This is true for CM9 final1, AOSP ICS final2 and AOSP JB beta1.
Hope you can fix it or enlight me how I can disable haptic feedback.

**Comment by guilherme-blatt** [comment]
Go System settings>Language & input> click the Android Keyboard settings icon and disable vibrate/sound on keypress. Hope i helped

**Comment by mexipower** [comment]
that bug its only after change the brightness. if u cant turn off even after reboot, then reinstall the rom.
in AOSP its a minimum bug, if you change the brightness, and u lock the cellphone, the light will stay on, but it will off when you unlock the cellphone, and if you change the brightness (thats the conditiion to the button cant turn off) and press the button it will be normal light (i mean, the buttons will turn off/on normally).

**Comment by empty4u** [comment]
Hello,

I think I explain my problem better. Everytime I write a SMS or email on 
every keypress the device vibrates. I want to turn this off. Normally 
under system -> settings -> language & input there is an option to 
change vibration behavior on keypress. There it is on my old "official" 
CM7.2 ROM. In your ROMs I can't find a corresponding setting. So perhaps 
it's not a bug but a missing option. Could you tell me how to reach this 
settings?
Thanks for your effort.

Am 07.04.2013 01:18, schrieb mexipower:

**Comment by guilherme-blatt** [comment]
after reaching "language & input" press the android keyboard settings key

**Comment by empty4u** [comment]
Sorry, I'm so stupid. Perhaps I should have tried to push the button 
right and not the keyboard-button itself.:-[
Yes, you can laugh now and close the case. ;o)
Thank you.

Am 07.04.2013 01:18, schrieb mexipower:

**Comment by guilherme-blatt** [comment]
dont worry, everyone has stupid moments, and i wont laugh at u hahah
