### ISSUE TITLE
MMS problem     CM9

### ISSUE THREAD

**Issue by ssovukluk1** [MaclawStudio/aosp#197]
Hey, first my language is not english so I can  make some mistakes sorry about that. there is a problem at sending and downloading mms. I thing that problem is in all roms. I tried some solves but they didn't work. When I send a mms its waiting in sending or while I was downloading a mms it waiting in downloading. sorry for my bad english. can you fix it?

**Comment by ssovukluk1** [comment]
Does no one have a problem with that?

**Comment by manuhuerta** [comment]
Same problem here

**Comment by ragerage** [comment]
i also have same problem.I think this problem is in all ROMs.Fix It.

**Comment by ssovukluk1** [comment]
Yeah this is in all roms. It should be fix. I usualy send mms. but cm9 final 2 released I think cm9 final 2 too have this problem
