### ISSUE TITLE
[AOSP final 2] batterie problem using 3g

### ISSUE THREAD

**Issue by DoBi** [MaclawStudio/aosp#200]
Today i noticed that the batterie from my ace lost 87% in 4 hours. It was not doing this any time befor, but today i was outside my wireless lan, so the phone used 3g.
I haven't done anything with it in this 4 hours. This was veey strange..

**Comment by guilherme-blatt** [comment]
1-you may need to calibrated your battery (just search on google how to)
2- when wifi is enabled, it uses battery even if not connected to a network
3- ace battery suck for me too :(
(sry for my english)

**Comment by menboi1** [comment]
me too i do all the calibration but nothing, and then  flash another rom and the battery is great
i think (i dont know is my opinion) is kernel problem
Please marcin fix it :+1:

**Comment by jcperes** [comment]
According to Google's engineers, battery calibration is a myth! Don't waste your time with that!
About the 3G, it drains energy really fast in every rom I have ever used so far. There won't be any miraculous solution for that!
