### ISSUE TITLE
[CM10 Galaxy S3 Mini] Youtube

### ISSUE THREAD

**Issue by Toastynator** [MaclawStudio/aosp#207]
whenever I try to view any videos (lq and hq) using the youtube app (testet with up to date and older versions of the app) I get an error saying:"There was an error while playing Touch to retry" 
I am guessing this has to do with the video acceleration ( not working as described) but just in case it doesn't....

ROM-version: alpha1
Kernel version: 3.0.31+maclaw@vb-debian#1 Sat Apr 6 17:17:07 CEST 2013

**Comment by maclaw** [comment]
Yes, it mentioned as video hw acceleration is not working. Closed.
