### ISSUE TITLE
Weather on lock screen at Ace5830 with CM9 final3

### ISSUE THREAD

**Issue by ga4** [MaclawStudio/aosp#208]
No location found!
On CM9final2 work's fine!

**Comment by ga4** [comment]
On CM9final2 work's fine!

**Comment by guilherme-blatt** [comment]
try to write the location like this: New York, NY. If u have already done that, i dont know what the problem is.

**Comment by ga4** [comment]
I write inclussive New York and the answer is :cannot retrieve location!
On CM9 final 2,I have no problem with this weather!
Internet conection works great.
Thank you!

**Comment by maclaw** [comment]
It's issue in CM code, not our fault.
