### ISSUE TITLE
Google map ?

### ISSUE THREAD

**Issue by s4m4n** [MaclawStudio/aosp#22]
Google map doesn't show me anything and it says 'loading' , but I can open maps.google.com withing the browser and everything is working fine. I hadn't this issue with other ROMs and also I had cleared google map cache and it didn't worked.

anyone experiencing this issue ? thoughts ?

Thanks.

**Comment by richardxtc** [comment]
Does your gps "lock on"??

**Comment by s4m4n** [comment]
it locks in a a few seconds , pretty fast :-) I tied with maps.google.com in the default browser.
