### ISSUE TITLE
bugs with aosp

### ISSUE THREAD

**Issue by fake220** [MaclawStudio/aosp#28]
So have tested with aosp rc2:
1.When i listen to music and with wifi my phone lag so much...
2.When music play and i block screen it don't show the home sceern only music vidget in locker.
3. Problems with wifi can't access to google market.

**Comment by Vyzygota** [comment]
I have once problem no 3.
I get info: "Your account need to be verified!"
But in the same day i download something from google play.
It was wired!

after restart it goes.
