### ISSUE TITLE
ICS Native Encryption isn't working

### ISSUE THREAD

**Issue by rcolaco** [MaclawStudio/aosp#3]
It seems that if we choose to encrypt our phone, it will ask to choose PIn and after that apear "droid" that will remain forever...

**Comment by maclaw** [comment]
It needs hw support afaik, so there's no chance for that function. Also it's only extra feature, which not exists on original software.

**Comment by rcolaco** [comment]
You mean that the hardware of Gio does not support this feature? The main purpose of the update, from my side, it was this feature! I need to access email account at my company and security policies only allow access from encrypted devices.
