### ISSUE TITLE
some bugs that I have! :)

### ISSUE THREAD

**Issue by alexelpan** [MaclawStudio/aosp#32]
Hi, I have some small problems
1. - Sometimes my screen flashes and freezes (once the display strange colors present in the notification area and blinking)
2. - Sometimes the keyboard does not appear on the screen
3.-The notification area sometimes gets frozen image but if you can access the notification
4. - A few times I have been freezing the phone with some applications like facebook, waze, twitter, even with the settings and messages and I have to remove the battery to restart the phone.
I did the full erase dalkvik, battery, system, data, and factory reset when installing the rom (actually I installed the rom 2 times doing the same procedure to be sure no installation error).
The only downside is that my battery is not working properly, and not hold a charge as before, hope it's not why I have these problems.
indeed the wifi was slow and sometimes turn not ignited.
excellent work, I hope you can guide me where I went wrong or what may be the fault I have.
my phone is a GT5830L, I hope the problem is not the phone model I have.
thank you very much for the help, keep up the good work!

**Comment by alexelpan** [comment]
by the way I'm Alex, that I send logs

**Comment by grkngrn** [comment]
Yes, I have some of this problems too. 
Sometimes;
1- notification area can't be seen
2- when someone calling me there is black screen, i can't see who is calling.
3- my screen flashes and freezes

**Comment by alexelpan** [comment]
not even a comment or something? only you closed it. please help me a bit to see what I'm doing wrong: (
thanks

**Comment by huzefa52** [comment]
yea same here with me too..when someone call us it dont show anything neither miscall..and while uninstalling application from application drawer it lags a lot ...do u also getting same probelm..while uninstalling

**Comment by MardonHH** [comment]
@alexelpan why a comment if the github bugtracker is not used the way it should!?
ONLY ONE BUG PER ISSUE!
