### ISSUE TITLE
need notification toggles

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#35]
maclaw and marcin u both are great.... can u please put notification toggles in ics aosp for galaxy ace... i know it is clean android.... but almost all of us need notification toggles inbuilt...or if u dont want to put in ics aosp notification toggles .....u can create a separate zip for  notification toggles....please ..and ways thanks for such a great  rom.....

**Comment by alexelpan** [comment]
you can use Notification Toggle from google play (https://play.google.com/store/apps/details?id=de.j4velin.notificationToggle&hl=es) :) this app works great!! even better than built in toggles from cyanogen or other roms

**Comment by huzefa52** [comment]
thanks for helping... :) i already have that application..but  it would be  more easy if its in build  notification toggles ....
