### ISSUE TITLE
A few video crash and color problems.

### ISSUE THREAD

**Issue by king5327** [MaclawStudio/aosp#36]
I watch videos. Lots of them.
Occasionally, my Gio crashes.
In earlier versions, it would crash at a rate of 1 crash for every 10 minutes of video watched.
In RC1, it took two straight hours for the same to occur. A good improvement, but not perfect.
Not confirmed with RC2, but it may still crash after a long amount of video.
Also, for some videos, a green streak is presented at the top of the screen, and all color is shifted down by its height. The bottom of the streak is not the full width of the screen, and all color gets moved to the right by that amount as well, wrapping around if needed. Example video with this: "Shatter (Curse of Pinkamena)" downloaded from YouTube using Tubemate. This IS confirmed in RC2.

Cheers,
king5327

**Comment by doomsded** [comment]
I have that problem too.

**Comment by king5327** [comment]
Which one, doomsded? I note two.
If it's the color problem, it only occurs when (I use MX Player to test this) h/w (hardware) mode is used. Does not occur with s/w (software) mode.
The crash problem occurs with both modes.
Did you try the video I pointed out, or a different one?
Also, Gio or Ace?

**Comment by MardonHH** [comment]
Its a omx lib related problem
