### ISSUE TITLE
Issues I found in RC2

### ISSUE THREAD

**Issue by ghost** [MaclawStudio/aosp#37]
I really like the rom, the perfomance, the look and feel etc, here are some things i found:
- USB tethering does not work, every time i tried to turn it on it said the setting app was force closed.
- video playing bug, when I'm playing videos with the gallery app there's some strange behavior in the background.
- Notificacion toogle included would be really really cool.
- Google Voice does not work for me, everytime i use it, there no answer from it.
- As other users said sometime android start to freeze, especially when i try to use google voice input and change to keyboard (I think that cause it, but I'm not sure).
- The app play music consume my battery charge fast :p, but it's really cool
- more options in the long press at main screen would be great.

**Comment by MardonHH** [comment]
1 bug per issue plz
