### ISSUE TITLE
couple problems 

### ISSUE THREAD

**Issue by raymuy** [MaclawStudio/aosp#38]
First of all i have to say that after trying so many roms for gio and this is the best! 
couple things: 
-the battery doesn't updates when the screen is off. you can leave fully charged phone on stand by for hours and then turn on the screen to see that it is still on 100% but after 2 minutes its updates to 60%. don't think wrong, the battery is great! but this problem makes the battery graph jumpy even though the battery is great. 

-another small thing, can you please add option to remove the Google search bar? i think that the device will be much more beautiful without it. 

thank you very much!

**Comment by Hielko-zz** [comment]
Battery jump also on my phone. And I also would like to remove Google search bar! Not urgent of course.

**Comment by s4m4n** [comment]
Same here !

**Comment by marius500** [comment]
Get holo launcher if u want to remove Google search bar...it's not that hard...

**Comment by raymuy** [comment]
why are did you close the issue? 
its an offer we want you to put in the rom 
why are you ignoring?
