### ISSUE TITLE
Not one, but two.

### ISSUE THREAD

**Issue by ikikinoko** [MaclawStudio/aosp#43]
It's one day of RC2 usage and I got two problems which are have fixed on changelog (might be not fully fixed). Let's start!
1. When booting finished, process com.android.phone suddenly stopped. That was not once, but every rebooting.
2. Some apps are stopped responding, especially for Gallery.

That's all what I report, I apologize if there is something bad on my talking or my report. I'm grateful for trying this release (smooth and some improvements on bluetooth) and I'm feeling appreciated to join in this bugtracker.

I've heard about AOSP JB, but it will be something 'superb' after made the stable AOSP ICS successfully.

**Comment by maclaw** [comment]
One issue per report.
