### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by shahabk** [MaclawStudio/aosp#5]
thank you for the new release. 
in each day i am refreshing the maclaw's page for more than 10 times to see if a release is made without VPN issue. you know it is crusial for us to connect internet in my dorm. i can not connect without it. 
thanks

**Comment by maclaw** [comment]
Accepted.

**Comment by s4m4n** [comment]
+1 for this . this feature is really needed :+1:

**Comment by SilenZ1** [comment]
+1 indeed! Also need the VPN option. Please include a compiled "tun.ko" especially for your custom made kernels. The tun.ko files from " Tun installer"  do not work. They all crash the phone.
