### ISSUE TITLE
WiFi not returning from sleep

### ISSUE THREAD

**Issue by ghost** [MaclawStudio/aosp#56]
When I set the Wifi configuration to disable when the phone is inactive, it does not reconnect after resume. It is needed to disable and enable again to reconnect.

Tested on Galaxy Ace with ICS AOSP RC2.

adb logcat in http://pastebin.ca/2310348

**Comment by lytvynenkosv** [comment]
Updated to latest ICS RC3, but issue still exists(GIO)
