### ISSUE TITLE
guys is not a issue .... 

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#62]
guys can any1 tell me how to change battery color exact like ics stock once..any third app..and guys can any1 tell me how do i chang application drawerr ui means like touchwiz 5.0 ..any zip...

plz help... love this rom ics aosp rc2.....

thanks maclaw. & marcin...

**Comment by MardonHH** [comment]
Its no issue and this is no discussion forum here.

**Comment by huzefa52** [comment]
yea i know its not a dicussion form here but ..any idea..??? plz..
