### ISSUE TITLE
3 bugs found..with images..

### ISSUE THREAD

**Issue by huzefa52** [MaclawStudio/aosp#70]
![20130218_203109](https://f.cloud.github.com/assets/3390901/167609/5f9fc24e-79dd-11e2-8ea8-ce30931a0750.jpg)

 while selecting home screen and lock screen wallpaper its shows nothing  and when i select any 1 of th oping its force close..
![20130218_203418](https://f.cloud.github.com/assets/3390901/167610/6004515a-79dd-11e2-8fb9-97746f5a58de.jpg)

2nd bug when changing brightness  and turning off screen back key softkey light stayed open 

![20130218_203524](https://f.cloud.github.com/assets/3390901/167611/6010564e-79dd-11e2-9c79-190fa7d83331.jpg)

3 bug in gallary / setting option is blank.....

in ics aosp rc3 

sorry for my bad english...

**Comment by jcperes** [comment]
2nd and 3rd bugs here too (on Ace).
But the 3rd one doesn't bother me too much, since the stock gallery can be replaced for QuickPic!

**Comment by ikikinoko** [comment]
yup, 2 and 3... too.
