### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by edmund200** [MaclawStudio/aosp#71]
when using the AOSP rom for SGA the screen starts flashing and icons disappear. sometimes the flashing stops, but the moment u touch the touch screen it flashes again.
this tends to happen mostly on youtube. in other ICS AOSP ROMS ticking the HW OVERLAYS fixes it, but your rom that have that option in the developer menu

**Comment by jcperes** [comment]
My Ace is running RC3 and that never happened

**Comment by edmund200** [comment]
i use youtube 24/7 and the screen starts to flickering after a couple of hours
