### ISSUE TITLE
Invisible Lockscreen buttons

### ISSUE THREAD

**Issue by edmund200** [MaclawStudio/aosp#72]
sometimes u cant see any of the lockscreen icons expect the background. but if your move your had where they are meant to be the the scrren unlocks.

ISSUE ON THE GALAXY ACE.
PLZZZ FIX SOON

**Comment by king5327** [comment]
Gio too.

One app that invokes this a lot is Youtube.

Often comes paired with invisible power menu (or the reboot menu in milder cases).
