### ISSUE TITLE
--removed--

### ISSUE THREAD

**Issue by edmund200** [MaclawStudio/aosp#86]
--removed--

**Comment by huzefa52** [comment]
dude u should respect maclaw and his amazing rom.. first of all he is providing us ics and jb..for free...and he closed this issue for a reason.... so plz shut up..and respect..maclaw and his work...and he is doing his best to provide a stable rom

**Comment by MardonHH** [comment]
This is no Bug.
MIND YOUR LANGUAGE

**Comment by edmund200** [comment]
--------REMOVED---------

Mind your language!
