### ISSUE TITLE
WIFI Bug

### ISSUE THREAD

**Issue by ZiadAk** [MaclawStudio/aosp#89]
The WiFi takes a lot of time to turn on. And after 2 to 3 On/Off cycles, the wifi will not turn on  anymore (was a bug in the Stock ROM also). (Sorry for reporting a lot of bugs but I really liked your work and I wish to help you get this ROM in a perfect shape)

**Comment by MardonHH** [comment]
If you had this behaviour on Stock. Maybe you should first flash the newest stock rom to get a newer baseband in your phone.

**Comment by ZiadAk** [comment]
I was running the latest stock (2.3.6) before flashing this ROM
