### ISSUE TITLE
I don't know what is 

### ISSUE THREAD

**Issue by marius500** [MaclawStudio/aosp#91]
Ok i have astro file manager... So i want to send an file with extension. Apk with bluetooth but when i tap share option it send's me to email.... Plese test it or atleast give me another file manager or something..... It only happens on file with.  Apk

**Comment by edmund200** [comment]
rename the file and put .apk at hte end of the name. works for me XD. if not use a different filemanager

**Comment by marius500** [comment]
u didn't understanded me...but nvm
