### ISSUE TITLE
Menu and Back Button 'Led' aren't Working (JB Alpha 1 - ACE)

### ISSUE THREAD

**Issue by ikikinoko** [MaclawStudio/aosp#98]
First of all, I'm shocked 'cause AOSP JB has released tonight even though it's still alpha. Beside there are some (important) system not working, I just wanna tell a problem. That's about Menu and Back Button, their led aren't working from first boot. It was strange and keep not working after reboot. Just try to re-install to ICS RC3 (they worked properly) and back to JB alpha 1 (they were off). About installation, I always do full wipe before install rom. That's all my problem here, sorry for my language.

But, of course I wanna give applause to this rom. Thank you.

**Comment by maclaw** [comment]
Can't you read news on Maclaw.pl?

**Comment by ikikinoko** [comment]
I did, I already read that issue when Alpha 2 had released. And I've been feeling it since Alpha 1.
