### ISSUE TITLE
Storage Setting Always Stopped Working (JB Alpha 1 - ACE)

### ISSUE THREAD

**Issue by ikikinoko** [MaclawStudio/aosp#99]
Yep, another problem: Settings has stopped working when open Settings -> Storage, so I cannot unmount sd card safetly.

**Comment by ghost** [comment]
I can verify and have logcat for this, hope this helps and maybe you will reopen the bug @maclaw 

03-13 20:43:48.159 D/AndroidRuntime( 6007): 
03-13 20:43:48.159 D/AndroidRuntime( 6007): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
03-13 20:43:48.159 D/AndroidRuntime( 6007): CheckJNI is OFF
03-13 20:43:48.299 D/dalvikvm( 6007): Trying to load lib libjavacore.so 0x0
03-13 20:43:48.309 D/dalvikvm( 6007): Added shared lib libjavacore.so 0x0
03-13 20:43:48.359 D/dalvikvm( 6007): Trying to load lib libnativehelper.so 0x0
03-13 20:43:48.359 D/dalvikvm( 6007): Added shared lib libnativehelper.so 0x0
03-13 20:43:49.229 D/AndroidRuntime( 6007): Calling main entry com.android.commands.am.Am
03-13 20:43:49.239 D/dalvikvm( 6007): Note: class Landroid/app/ActivityManagerNative; has 157 unimplemented (abstract) methods
03-13 20:43:49.319 D/AndroidRuntime( 6007): Shutting down VM
03-13 20:43:49.399 D/dalvikvm( 6007): GC_CONCURRENT freed 93K, 17% free 506K/604K, paused 19ms+0ms, total 71ms
03-13 20:43:50.359 D/dalvikvm( 5520): GC_CONCURRENT freed 399K, 48% free 4546K/8704K, paused 4ms+26ms, total 181ms
03-13 20:43:50.629 D/dalvikvm(  427): GC_FOR_ALLOC freed 1360K, 28% free 12704K/17528K, paused 556ms, total 564ms
03-13 20:43:50.839 W/IInputConnectionWrapper( 5520): showStatusIcon on inactive InputConnection
03-13 20:43:51.439 D/AndroidRuntime( 6033): 
03-13 20:43:51.439 D/AndroidRuntime( 6033): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
03-13 20:43:51.439 D/AndroidRuntime( 6033): CheckJNI is OFF
03-13 20:43:51.659 D/dalvikvm( 6033): Trying to load lib libjavacore.so 0x0
03-13 20:43:51.729 D/dalvikvm( 6033): Added shared lib libjavacore.so 0x0
03-13 20:43:51.809 D/dalvikvm( 5520): GC_CONCURRENT freed 555K, 49% free 4502K/8704K, paused 12ms+24ms, total 348ms
03-13 20:43:51.809 D/dalvikvm( 5520): WAIT_FOR_CONCURRENT_GC blocked 44ms
03-13 20:43:51.839 D/dalvikvm( 6033): Trying to load lib libnativehelper.so 0x0
03-13 20:43:51.839 D/dalvikvm( 6033): Added shared lib libnativehelper.so 0x0
03-13 20:43:52.219 D/dalvikvm( 5520): GC_CONCURRENT freed 668K, 51% free 4345K/8704K, paused 5ms+16ms, total 137ms
03-13 20:43:52.219 D/dalvikvm( 5520): WAIT_FOR_CONCURRENT_GC blocked 40ms
03-13 20:43:52.509 D/dalvikvm( 5520): GC_CONCURRENT freed 511K, 51% free 4345K/8704K, paused 7ms+4ms, total 130ms
03-13 20:43:52.509 D/dalvikvm( 5520): WAIT_FOR_CONCURRENT_GC blocked 37ms
03-13 20:43:52.859 D/AndroidRuntime( 6033): Calling main entry com.android.commands.am.Am
03-13 20:43:52.879 D/dalvikvm( 6033): Note: class Landroid/app/ActivityManagerNative; has 157 unimplemented (abstract) methods
03-13 20:43:52.959 D/AndroidRuntime( 6033): Shutting down VM
03-13 20:43:52.969 D/dalvikvm( 6033): GC_CONCURRENT freed 93K, 17% free 506K/604K, paused 0ms+1ms, total 16ms
03-13 20:43:54.009 D/dalvikvm(  887): GC_FOR_ALLOC freed 932K, 28% free 6744K/9356K, paused 73ms, total 75ms
03-13 20:43:54.019 I/dalvikvm-heap(  887): Grow heap (frag case) to 8.339MB for 1286224-byte allocation
03-13 20:43:54.209 D/dalvikvm(  887): GC_CONCURRENT freed 6K, 25% free 7993K/10616K, paused 10ms+45ms, total 186ms
03-13 20:43:55.019 D/dalvikvm(  714): GC_CONCURRENT freed 501K, 41% free 4921K/8212K, paused 15ms+22ms, total 169ms
03-13 20:43:55.199 D/AndroidRuntime( 6023): 
03-13 20:43:55.199 D/AndroidRuntime( 6023): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
03-13 20:43:55.289 D/AndroidRuntime( 6023): CheckJNI is OFF
03-13 20:43:55.609 D/dalvikvm( 6023): Trying to load lib libjavacore.so 0x0
03-13 20:43:55.649 D/dalvikvm( 6023): Added shared lib libjavacore.so 0x0
03-13 20:43:55.749 D/dalvikvm( 6023): Trying to load lib libnativehelper.so 0x0
03-13 20:43:55.749 D/dalvikvm( 6023): Added shared lib libnativehelper.so 0x0
03-13 20:43:56.089 D/AndroidRuntime( 6034): 
03-13 20:43:56.089 D/AndroidRuntime( 6034): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
03-13 20:43:56.089 D/AndroidRuntime( 6034): CheckJNI is OFF
03-13 20:43:56.279 D/dalvikvm( 6034): Trying to load lib libjavacore.so 0x0
03-13 20:43:56.309 D/dalvikvm( 6034): Added shared lib libjavacore.so 0x0
03-13 20:43:56.329 D/dalvikvm( 6034): Trying to load lib libnativehelper.so 0x0
03-13 20:43:56.329 D/dalvikvm( 6034): Added shared lib libnativehelper.so 0x0
03-13 20:43:56.909 I/ActivityManager(  427): Process com.android.vending (pid 5825) has died.
03-13 20:43:57.179 D/AndroidRuntime( 6023): Calling main entry com.android.commands.am.Am
03-13 20:43:57.189 D/dalvikvm( 6023): Note: class Landroid/app/ActivityManagerNative; has 157 unimplemented (abstract) methods
03-13 20:43:57.229 D/AndroidRuntime( 6023): Shutting down VM
03-13 20:43:57.259 D/dalvikvm( 6023): GC_CONCURRENT freed 93K, 17% free 506K/604K, paused 1ms+1ms, total 23ms
03-13 20:43:57.379 D/AndroidRuntime( 6034): Calling main entry com.android.commands.am.Am
03-13 20:43:57.379 D/dalvikvm( 6034): Note: class Landroid/app/ActivityManagerNative; has 157 unimplemented (abstract) methods
03-13 20:43:57.419 D/AndroidRuntime( 6034): Shutting down VM
03-13 20:43:57.439 D/dalvikvm( 6034): GC_CONCURRENT freed 93K, 17% free 506K/604K, paused 0ms+0ms, total 16ms
03-13 20:44:01.619 D/dalvikvm(  887): GC_CONCURRENT freed 2855K, 38% free 6337K/10220K, paused 4ms+19ms, total 114ms
03-13 20:44:02.319 I/ActivityManager(  427): START u0 {act=android.settings.SETTINGS flg=0x10200000 cmp=com.android.settings/.Settings} from pid 887
03-13 20:44:02.459 I/ActivityManager(  427): Start proc com.android.settings for activity com.android.settings/.Settings: pid=6066 uid=1000 gids={41000, 1015, 1028, 3002, 3001, 3003, 3007}
03-13 20:44:02.549 D/dalvikvm(  100): GC_EXPLICIT freed 39K, 51% free 4096K/8208K, paused 5ms+16ms, total 93ms
03-13 20:44:02.599 W/InputMethodManagerService(  427): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41190fe0 attribute=android.view.inputmethod.EditorInfo@41107700, token = android.os.BinderProxy@40f42ec0
03-13 20:44:02.629 D/dalvikvm(  100): GC_EXPLICIT freed <1K, 51% free 4096K/8208K, paused 4ms+12ms, total 86ms
03-13 20:44:02.719 D/dalvikvm(  100): GC_EXPLICIT freed <1K, 51% free 4096K/8208K, paused 3ms+10ms, total 87ms
03-13 20:44:02.839 E/Trace   ( 6066): error opening trace file: No such file or directory (2)
03-13 20:44:04.009 D/BluetoothManagerService(  427): Message: 20
03-13 20:44:04.009 D/BluetoothManagerService(  427): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@4144bde0:true
03-13 20:44:04.049 D/BluetoothAdapter( 6066): 1089309832: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:04.049 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:04.069 W/ContextImpl( 6066): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothInputDevice.<init>:240 android.bluetooth.BluetoothAdapter.getProfileProxy:1161 com.android.settings.bluetooth.LocalBluetoothAdapter.getProfileProxy:94 
03-13 20:44:04.079 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:04.079 D/BluetoothPan( 6066): BluetoothPan() call bindService
03-13 20:44:04.079 D/BluetoothPan( 6066): BluetoothPan(), bindService called
03-13 20:44:04.079 W/ContextImpl( 6066): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothPan.<init>:141 android.bluetooth.BluetoothAdapter.getProfileProxy:1164 com.android.settings.bluetooth.PanProfile.<init>:73 
03-13 20:44:04.089 D/dalvikvm( 5520): GC_CONCURRENT freed 344K, 48% free 4388K/8360K, paused 3ms+21ms, total 77ms
03-13 20:44:04.089 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:04.099 D/LocalBluetoothProfileManager( 6066): LocalBluetoothProfileManager construction complete
03-13 20:44:04.099 W/ContextImpl( 6066): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothPbap.<init>:161 com.android.settings.bluetooth.PbapServerProfile.<init>:68 com.android.settings.bluetooth.LocalBluetoothProfileManager.<init>:124 
03-13 20:44:04.109 D/BluetoothAdapter( 6066): 1089309832: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:04.109 D/BluetoothAdapter( 6066): 1089309832: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:04.219 D/libEGL  ( 6066): loaded /system/lib/egl/libEGL_adreno200.so
03-13 20:44:04.249 D/libEGL  ( 6066): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
03-13 20:44:04.259 D/libEGL  ( 6066): loaded /system/lib/egl/libGLESv2_adreno200.so
03-13 20:44:04.359 D/OpenGLRenderer( 6066): Enabling debug mode 0
03-13 20:44:04.399 D/WifiService(  427): setWifiEnabled: true pid=6066, uid=1000
03-13 20:44:04.419 D/BluetoothAdapter( 6066): 1089309832: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:04.779 I/ActivityManager(  427): Displayed com.android.settings/.Settings: +2s355ms
03-13 20:44:12.709 I/ActivityManager(  427): START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from pid 6066
03-13 20:44:12.839 D/dalvikvm(  427): GC_FOR_ALLOC freed 849K, 28% free 12716K/17528K, paused 110ms, total 116ms
03-13 20:44:13.449 I/ActivityManager(  427): Displayed com.android.settings/.SubSettings: +576ms
03-13 20:44:13.839 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Android) returned 2633728
03-13 20:44:13.859 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Podcasts) returned 8192
03-13 20:44:13.869 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/DCIM) returned 8192
03-13 20:44:13.909 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0) returned 460398592
03-13 20:44:13.909 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Ringtones) returned 8192
03-13 20:44:13.939 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Movies) returned 8192
03-13 20:44:13.959 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Alarms) returned 8192
03-13 20:44:13.969 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Music) returned 8192
03-13 20:44:13.999 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Notifications) returned 8192
03-13 20:44:14.019 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Pictures) returned 5316608
03-13 20:44:14.019 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0/Download) returned 1204224
03-13 20:44:14.039 D/StorageMeasurement( 6066): getDirectorySize(/storage/sdcard0) returned 460398592
03-13 20:44:15.009 D/AndroidRuntime( 6066): Shutting down VM
03-13 20:44:15.009 W/dalvikvm( 6066): threadid=1: thread exiting with uncaught exception (group=0x40a8e930)
03-13 20:44:15.009 E/AndroidRuntime( 6066): FATAL EXCEPTION: main
03-13 20:44:15.009 E/AndroidRuntime( 6066): java.lang.NullPointerException
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at com.android.settings.deviceinfo.StorageVolumePreferenceCategory.totalValues(StorageVolumePreferenceCategory.java:313)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at com.android.settings.deviceinfo.StorageVolumePreferenceCategory.updateDetails(StorageVolumePreferenceCategory.java:330)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at com.android.settings.deviceinfo.StorageVolumePreferenceCategory$1.handleMessage(StorageVolumePreferenceCategory.java:96)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at android.os.Looper.loop(Looper.java:137)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at android.app.ActivityThread.main(ActivityThread.java:5041)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at java.lang.reflect.Method.invokeNative(Native Method)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at java.lang.reflect.Method.invoke(Method.java:511)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
03-13 20:44:15.009 E/AndroidRuntime( 6066):     at dalvik.system.NativeStart.main(Native Method)
03-13 20:44:15.019 W/ActivityManager(  427):   Force finishing activity com.android.settings/.SubSettings
03-13 20:44:15.549 W/ActivityManager(  427): Activity pause timeout for ActivityRecord{40f36080 u0 com.android.settings/.SubSettings}
03-13 20:44:17.549 I/Process ( 6066): Sending signal. PID: 6066 SIG: 9
03-13 20:44:17.559 I/ActivityManager(  427): Process com.android.settings (pid 6066) has died.
03-13 20:44:17.569 I/WindowState(  427): WIN DEATH: Window{41038b40 u0 com.android.settings/com.android.settings.SubSettings}
03-13 20:44:17.599 I/ActivityManager(  427): Start proc com.android.settings for activity com.android.settings/.Settings: pid=6093 uid=1000 gids={41000, 1015, 1028, 3002, 3001, 3003, 3007}
03-13 20:44:17.689 E/Trace   ( 6093): error opening trace file: No such file or directory (2)
03-13 20:44:17.899 D/BluetoothManagerService(  427): Message: 20
03-13 20:44:17.899 D/BluetoothManagerService(  427): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@40f76800:true
03-13 20:44:17.909 D/BluetoothAdapter( 6093): 1089243736: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:17.909 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:17.919 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:17.919 D/BluetoothPan( 6093): BluetoothPan() call bindService
03-13 20:44:17.919 D/BluetoothPan( 6093): BluetoothPan(), bindService called
03-13 20:44:17.919 W/ContextImpl( 6093): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothInputDevice.<init>:240 android.bluetooth.BluetoothAdapter.getProfileProxy:1161 com.android.settings.bluetooth.LocalBluetoothAdapter.getProfileProxy:94 
03-13 20:44:17.919 W/ContextImpl( 6093): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothPan.<init>:141 android.bluetooth.BluetoothAdapter.getProfileProxy:1164 com.android.settings.bluetooth.PanProfile.<init>:73 
03-13 20:44:17.929 D/BluetoothManagerService(  427): Message: 30
03-13 20:44:17.929 D/LocalBluetoothProfileManager( 6093): LocalBluetoothProfileManager construction complete
03-13 20:44:17.929 W/ContextImpl( 6093): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1406 android.content.ContextWrapper.bindService:473 android.bluetooth.BluetoothPbap.<init>:161 com.android.settings.bluetooth.PbapServerProfile.<init>:68 com.android.settings.bluetooth.LocalBluetoothProfileManager.<init>:124 
03-13 20:44:17.939 D/BluetoothAdapter( 6093): 1089243736: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:17.939 D/BluetoothAdapter( 6093): 1089243736: getState() :  mService = null. Returning STATE_OFF
03-13 20:44:18.039 D/libEGL  ( 6093): loaded /system/lib/egl/libEGL_adreno200.so
03-13 20:44:18.049 D/libEGL  ( 6093): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
03-13 20:44:18.049 D/libEGL  ( 6093): loaded /system/lib/egl/libGLESv2_adreno200.so
03-13 20:44:18.089 D/OpenGLRenderer( 6093): Enabling debug mode 0
03-13 20:44:18.409 W/InputMethodManagerService(  427): Got RemoteException sending setActive(false) notification to pid 6066 uid 1000
03-13 20:44:18.419 I/ActivityManager(  427): Displayed com.android.settings/.Settings: +2s870ms
03-13 20:44:19.879 D/dalvikvm(  427): GC_FOR_ALLOC freed 1594K, 27% free 12952K/17528K, paused 116ms, total 119ms
03-13 20:44:20.299 W/InputMethodManagerService(  427): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41117030 (uid=1000 pid=6093)
03-13 20:44:20.429 I/ActivityManager(  427): Displayed com.android.launcher/com.android.launcher2.Launcher: +533ms
